name: pgnet
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2023.08.22=h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py312h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=py312h06a4308_0
  - ipython=8.15.0=py312h06a4308_0
  - jedi=0.18.1=py312h06a4308_1
  - jinja2=3.1.3=py312h06a4308_0
  - jupyter_core=5.5.0=py312h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py312h06a4308_0
  - networkx=3.1=py312h06a4308_0
  - openssl=3.0.13=h7f8727e_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - prompt-toolkit=3.0.36=py312h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - python=3.12.2=h996f2a0_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=25.1.0=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py312h5eee18b_0
  - traitlets=5.7.1=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==1.8.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - av==15.0.0
      - babel==2.17.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.2
      - certifi==2024.2.2
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - fastjsonschema==2.21.1
      - fonttools==4.50.0
      - fqdn==1.5.1
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.175.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - h11==0.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.33.2
      - idna==3.6
      - imageio==2.37.0
      - ipdb==0.13.13
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jiter==0.8.2
      - joblib==1.3.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - matplotlib==3.8.3
      - mistune==3.1.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.4
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.59.4
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - pillow==10.2.0
      - prometheus-client==0.22.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==5.9.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pyee==13.0.0
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-ffmpeg==2.0.12
      - python-json-logger==3.3.0
      - pytz==2024.1
      - qwen-vl-utils==0.0.8
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.26.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.25.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.47.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - statsmodels==0.14.4
      - sympy==1.14.0
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tifffile==2025.1.10
      - tinycss2==1.4.0
      - tokenizers==0.21.2
      - torch==2.2.0+cu118
      - torchaudio==2.2.0+cu118
      - torchvision==0.17.0+cu118
      - tqdm==4.66.2
      - transformers==4.51.3
      - triton==3.3.1
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - urllib3==2.2.1
      - wandb==0.23.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - yacs==0.1.8
